@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/x-www-form-urlencoded
@userId = 6291096eee7ca0492ca3dfa2


GET http://{{host}}/  HTTP/1.1

###
GET http://{{host}}/api/users

###

GET http://{{host}}/api/users/{{userId}}/logs HTTP/1.1
  ?from=1990-01-01
  &to=2022-04-01
  &limit=100
###


GET http://{{host}}/api/users/2  HTTP/1.1

###

POST http://{{host}}/api/users HTTP/1.1
Content-Type: {{contentType}}

username=Phillip300

###
POST http://{{host}}/api/users/{{userId}}/exercises HTTP/1.1
Content-Type: {{contentType}}

description=climbing
&duration=20
&date=2022-1-13
